import { mkdirSync, writeFileSync, existsSync } from 'fs'
import { join, resolve } from 'path'
import { colors, symbols, header } from './ui.js'

const PACKAGE_JSON = (name: string) => JSON.stringify({
  name: name,
  version: '0.1.0',
  description: `MCP server: ${name}`,
  type: 'module',
  bin: { [name]: './dist/index.js' },
  scripts: {
    build: 'tsup',
    dev: 'tsup --watch',
  },
  keywords: ['mcp', 'model-context-protocol', 'ai', 'tools'],
  license: 'MIT',
  dependencies: {
    '@modelcontextprotocol/sdk': '^1.0.0',
  },
  devDependencies: {
    '@types/node': '^22.0.0',
    tsup: '^8.3.0',
    typescript: '^5.6.0',
  },
}, null, 2) + '\n'

const TSCONFIG = JSON.stringify({
  compilerOptions: {
    target: 'ES2022',
    module: 'ESNext',
    moduleResolution: 'bundler',
    lib: ['ES2022'],
    outDir: './dist',
    rootDir: './src',
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    resolveJsonModule: true,
  },
  include: ['src/**/*'],
}, null, 2) + '\n'

const TSUP_CONFIG = `import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  target: 'node18',
  outDir: 'dist',
  clean: true,
  dts: true,
  banner: { js: '#!/usr/bin/env node' },
})
`

const SERVER_TEMPLATE = (name: string) => `#!/usr/bin/env node
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js'

const server = new Server(
  { name: '${name}', version: '0.1.0' },
  { capabilities: { tools: {} } }
)

// ─── Define your tools here ───────────────────────────────
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: 'hello',
        description: 'A sample tool that returns a greeting',
        inputSchema: {
          type: 'object',
          properties: {
            name: { type: 'string', description: 'Name to greet' },
          },
          required: ['name'],
        },
      },
    ],
  }
})

// ─── Handle tool calls ────────────────────────────────────
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params

  switch (name) {
    case 'hello': {
      const who = (args as any)?.name || 'world'
      return {
        content: [{ type: 'text', text: \`Hello, \${who}! from ${name}\` }],
      }
    }
    default:
      return { content: [{ type: 'text', text: \`Unknown tool: \${name}\` }] }
  }
})

// ─── Start the server ─────────────────────────────────────
async function main() {
  const transport = new StdioServerTransport()
  await server.connect(transport)
  console.error('${name} MCP server running on stdio')
}

main().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
`

const README = (name: string) => `# ${name}

An MCP (Model Context Protocol) server generated by \`mcp-hub init\`.

## Install

\`\`\`bash
npm install
npm run build
\`\`\`

## Use with Claude Desktop

Add to \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "${name}": {
      "command": "node",
      "args": ["${join(process.cwd(), name, 'dist', 'index.js')}"]
    }
  }
}
\`\`\`

## Tools

- **hello** — A sample tool that returns a greeting

## License

MIT
`

const GITIGNORE = `node_modules/
dist/
*.tsbuildinfo
.env
.DS_Store
`

export function initServer(name: string, options: { path?: string }): void {
  console.log(header(`Scaffolding ${name}`))

  const basePath = options.path ? resolve(options.path) : process.cwd()
  const serverPath = join(basePath, name)

  if (existsSync(serverPath)) {
    console.log(`  ${symbols.cross} Directory already exists: ${colors.red(serverPath)}\n`)
    return
  }

  // Create directory structure
  mkdirSync(join(serverPath, 'src'), { recursive: true })

  // Write files
  writeFileSync(join(serverPath, 'package.json'), PACKAGE_JSON(name))
  writeFileSync(join(serverPath, 'tsconfig.json'), TSCONFIG)
  writeFileSync(join(serverPath, 'tsup.config.ts'), TSUP_CONFIG)
  writeFileSync(join(serverPath, 'src', 'index.ts'), SERVER_TEMPLATE(name))
  writeFileSync(join(serverPath, 'README.md'), README(name))
  writeFileSync(join(serverPath, '.gitignore'), GITIGNORE)

  console.log(`  ${symbols.check} Created ${colors.bold(name)} at:`)
  console.log(`  ${colors.gray(serverPath)}\n`)
  console.log(`  ${colors.bold('Next steps:')}`)
  console.log(`    ${colors.gray('cd')} ${name}`)
  console.log(`    ${colors.gray('npm install')}`)
  console.log(`    ${colors.gray('npm run build')}`)
  console.log(`    ${colors.gray('node dist/index.js')}  ${colors.gray('# test it')}`)
  console.log(`\n  ${colors.gray('Then add to your AI client config and test with Claude/Cursor.')}`)
  console.log(`  ${colors.gray('When ready, submit to MCP Hub:')}`)
  console.log(`  ${colors.gray('https://github.com/e2sy/mcp-hub/blob/main/CONTRIBUTING.md')}\n`)
}
